@startuml
title UML-Klassendiagramm "Binary Search Tree" 
skinparam Nodesep 100
hide circle 
hide <<notImplemented>> stereotype
<style>
.notImplemented {
    BackgroundColor GhostWhite
}
</style> 
class Node {
    + key 
    + value 
}
class BST {
    + root
    + search() 
    + insert() 
}


Node -[hidden]> BST
 
BST "1" *-- "*" Node 

@enduml